### ISSUE TITLE
how to fuzz indication Handle

### ISSUE THREAD

**Issue by NadSo** [nccgroup/BLE-Replay#1]
Hello,
I have two questions:
1) I have my Android Smartphone communicating with my BLE Device via BLE. While sniffing the connection I noticed that my Android sends indication characteristic with Handles in order to control the LED and do not send any Writes characteristics. So my Question is do you if it is possible to extend or somthing like that the Replay tool so it could also works for indication Handle?

2) I have two BLE Boards communicating to each other via BLE. One controls the LED of the other by sending write characteristics. I want to use BLE-Replay for fuzzing it but the problem is I can just sniff it and have the PCAP file not the log File since I am not using a Smartphone . So my question is: Is it possible to make the BLE-Replay work with the PCAP file too? Or it only works with log File? Is there a way to transform Pcap in log?

Thank you

**Comment by Taolaw** [comment]
> Hello,
> I have two questions:
> 
> 1. I have my Android Smartphone communicating with my BLE Device via BLE. While sniffing the connection I noticed that my Android sends indication characteristic with Handles in order to control the LED and do not send any Writes characteristics. So my Question is do you if it is possible to extend or somthing like that the Replay tool so it could also works for indication Handle?
> 2. I have two BLE Boards communicating to each other via BLE. One controls the LED of the other by sending write characteristics. I want to use BLE-Replay for fuzzing it but the problem is I can just sniff it and have the PCAP file not the log File since I am not using a Smartphone . So my question is: Is it possible to make the BLE-Replay work with the PCAP file too? Or it only works with log File? Is there a way to transform Pcap in log?
> 
> Thank you

My problem is worse than you, I can't run `BLE-Replay.py` directly. Looks like this
```bash
Traceback (most recent call last):
   File "ble-replay.py", line 1, in <module>
     Import hci_parser
   File "/root/code/BLE-Replay-master/hci_parser.py", line 3, in <module>
     Import util
   File "/root/code/BLE-Replay-master/util.py", line 4, in <module>
     From blesuite.bleServiceManager import bleServiceWriteToHandle
ImportError: No module named bleServiceManager
```
But I can't find any string information about `bleServiceManager` in `BLEsuite`. Have you had any similar problems? I need someone to help me, thank you.
